artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: http://github.com/kk06112001/data/raw/refs/heads/main/healthcare-dataset-stroke-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/healthcare-dataset-stroke-data.csv
  STATUS_FILE: artifacts/data_validation/status.txt